language: python

python:
  - "3.4"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: 
  - "pip install -r requirements_test.txt --use-mirrors"

script:
    - "flake8 ."
    - "SECRET_KEY=test DATABASE_URL=sqlite:///test.db coverage run --source='.' manage.py test"

after_success: coveralls
